
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/private/var/folders/ks/_614mn9d3c53zg_y00d9md840000gn/T/AppTranslocation/96E5E032-80E3-4A4B-94D0-EB2343CB2F60/d/CMake.app/Contents/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.5.0 - arm64
...
